from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any, Literal
from datetime import datetime
from enum import Enum

class IntentType(str, Enum):
    """
    Formalized intent types for the system.
    This replaces the legacy regex-based Intent enum.
    """
    GENERATE_CODE = "generate_code"
    GENERATE_VIDEO = "generate_video"
    REVIEW_CODE = "review_code"
    DEPLOY = "deploy"
    CHECK_STATUS = "check_status"
    LIST_TASKS = "list_tasks"
    CLARIFY = "clarify"
    PLAN = "plan" # New intent for dynamic planning
    UNKNOWN = "unknown"

class DetectedIntent(BaseModel):
    """
    Represents the outcome of the intent detection process.
    """
    intent_type: IntentType
    raw_intent: str = Field(..., description="The raw intent string from the LLM or detector")
    confidence: float = Field(..., ge=0.0, le=1.0)
    agent_name: Optional[str] = Field(None, description="The specific agent identified, if any")
    reasoning: Optional[str] = None

class PlanStep(BaseModel):
    """
    A single step in a generated plan.
    """
    step_number: int
    agent_role: str
    description: str
    estimated_duration_ms: Optional[int] = None
    required_inputs: List[str] = Field(default_factory=list)

class Plan(BaseModel):
    """
    A full execution plan generated by the PlannerAgent.
    """
    task_description: str
    steps: List[PlanStep]
    confidence: float = Field(..., ge=0.0, le=1.0)
    reasoning: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)

class ExecutionOutcome(BaseModel):
    """
    The result of executing a plan or a single action.
    """
    success: bool
    status: Literal["completed", "failed", "rejected", "error"]
    output: Dict[str, Any]
    error: Optional[str] = None
    steps_completed: int = 0
    duration_ms: int
    pipeline_id: Optional[str] = None

class InteractionRecord(BaseModel):
    """
    A comprehensive record of a single user interaction.
    This serves as the single source of truth for audit and telemetry.
    """
    trace_id: str
    user_id: str
    request_message: str
    detected_intent: DetectedIntent
    plan: Optional[Plan] = None
    execution_outcome: Optional[ExecutionOutcome] = None
    guardrail_decisions: List[Dict[str, Any]] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=datetime.utcnow)

