from .base_agent import BaseAgent, AgentResponse
from typing import Dict, Any, List
from ..services.contracts import Plan, PlanStep

class PlannerAgent(BaseAgent):
    """
    The PlannerAgent is responsible for breaking down complex user requests
    into a sequence of executable steps for other agents.
    """

    def run(self, input_data: Dict[str, Any]) -> AgentResponse:
        """
        Takes a user request and generates a plan.
        """
        # TODO: Implement the actual planning logic using an LLM call.
        # For now, this is a placeholder.
        
        request = input_data.get("request", "")
        
        # Placeholder logic:
        steps = []
        step_counter = 1
        
        if "code" in request.lower():
            steps.append(PlanStep(
                step_number=step_counter,
                agent_role="code_writer",
                description="Generate the requested code.",
                required_inputs=["requirement"]
            ))
            step_counter += 1
            
        if "review" in request.lower():
            steps.append(PlanStep(
                step_number=step_counter,
                agent_role="code_reviewer",
                description="Review the generated code.",
                required_inputs=["code"]
            ))
            step_counter += 1

        # Create the strict Plan object
        plan = Plan(
            task_description=request,
            steps=steps,
            confidence=0.9,
            reasoning="This is a placeholder plan generated by simple keyword matching."
        )

        return AgentResponse(
            agent="planner_agent",
            status="success",
            output=plan.dict() # Return dictionary representation for JSON serialization
        )
